language: node_js
node_js:
  - 0.8
  - 0.10
  - 0.11
notifications:
  email: false
addons:
  code_climate:
    repo_token: hJG9rRGiGmdH55VkaGkbaovmAd9heKNyi
after_script:
  - cat lcov.info | codeclimate
