language: node_js
node_js:
  - 0.8
  - 0.10
  - 0.11
notifications:
  email: false
install:
  - npm install istanbul -g
  - npm install codeclimate-test-reporter -g
after_success:
  - istanbul cover test.js --report lcovonly
  - CODECLIMATE_REPO_TOKEN=21f22d9d5941a54b1a028f91a7fc75f1104c514d4f05df6a8095777d2ee58ada codeclimate < coverage/lcov.info
